site_name: Quann
# site_url: https://github.com/ltq525/blog_site
# site_author: 权


repo_url: https://github.com/ltq525/blog_site
repo_name: Github_Code
copyright: Copyright &copy; Hello World - 2023 Quann
nav:
  - 简介:
    - blog/项目搭建.md
  - 博客:
    - Markdown基础教程: blog/Markdown基础教程.md
    - Linux入门命令: blog/Linux入门命令.md
    - Tmux使用方法: blog/Tmux使用方法.md
    - Vim基本命令: blog/Vim基本命令.md
    - Shell语法: blog/Shell语法.md
    - SSH远程登录: blog/SSH远程登录.md
    - Git基础使用命令: blog/Git基础命令.md
    - Thrift微服务RPC框架: blog/Thrift微服务RPC框架.md
    - Docker入门教程: blog/Docker入门基础.md
    - WSL子系统使用: blog/WSL子系统使用.md
    - Ubuntu中的ufw防火墙手册: blog/Ubuntu中的ufw防火墙手册.md
    - Breed_web不死鸟: blog/Breed_web不死鸟.md
    - Openwrt云编译固件教程: blog/Openwrt云编译固件教程.md
    - Openwrt_Luci插件解析: blog/Openwrt_Luci插件解析.md
    - Nginx部署: blog/Nginx部署.md
    - Tailscale内网穿透: blog/Tailscale实现内网穿透.md
    - Frp内网穿透: blog/Frp内网穿透.md
  - 项目:
    - 球球作战小游戏: project/球球作战小游戏.md
  - 算法:
    - 三分查找: algorithm/三分查找.md
    - 平衡查找树: algorithm/平衡查找树.md
    - 七大排序: algorithm/七大排序.md
    - 树链剥分: algorithm/树链剥分.md
    - KMP字符串匹配: algorithm/KMP字符串匹配.md
  - 设计模式: 
    - 设计原则: design_patterns/设计原则.md
    - 设计模式: design_patterns/设计模式.md
    
    

theme:
  name: material
  logo: logo/xianzi.png
  favicon: logo/xianzi.png
  language: zh
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  features:
    - navigation.instant 
    - header.autohide  # 自动隐藏
    #- announce.dismiss # 呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking # 地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs # 顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    #- navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - navigation.expand # 打开Tab时左侧目录全部展开
    #- navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share # 搜索分享按钮
    - content.code.annotate
    - content.tabs.link
    - content.code.copy # 文本复制
    - toc.follow
    #- toc.integrate # 屏蔽右边导航栏


  palette:

    # 日间模式
    - scheme: default
      primary: white # 头部菜单栏颜色
      accent: indigo # 交互文件高亮颜色
      toggle:
        icon: material/brightness-7
        name: 切换至夜间模式

    # 夜间模式
    - scheme: slate 
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-4
        name: 切换至夜间模式

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - meta # 支持Markdown文件上方自定义标题标签等
  #- pymdownx.betterem
  
  # 显示文本并定义上下标
  - pymdownx.caret 
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols # 智能符号
  - pymdownx.snippets
  - pymdownx.superfences 
    # 代码块高亮插件 可支持各类图
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys # 键盘符号
  - tables

  - pymdownx.critic:
      mode: view
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:  # latex支持 数学排版库
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true # 固定标题位置为当前位置

  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      use_pygments: true # JavaScript 语法突出显示
      pygments_lang_class: true # CSS 类识别代码块
      #linenums: true # 显示行号
      linenums_style: pymdownx-inline
      line_spans: __span
      #auto_title: true # 显示编程语言名称


#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg
#      options:
#        custom_icons:
#          - overrides/.icons


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/chrome
      link: https://chrome.com/
    - icon: fontawesome/brands/zhihu
      link: https://zhihu.com/
    - icon: fontawesome/brands/docker
      link: https://docker.com/
    - icon: fontawesome/brands/bilibili
      link: https://bilibili.com/
  homepage: https://github.com/
  # 隐藏下栏商标
  generator: false

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

  

  