site_name: Quann
site_url: https://github.com/ltq525/blog_site
site_author: 权

repo_url: https://github.com/ltq525/blog_site
repo_name: ltq525/blog_site

nav:
  - 简介:
    - blog/项目搭建.md
  - 博客:
    - Markdown基础教程: blog/Markdown基础教程.md
  - 网站:
    - site/index.md

theme:
  name: material
  logo: logo/xianzi.png
  favicon: logo/xianzi.png
  language: zh
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

  features:
    - navigation.instant 
    - header.autohide  #自动隐藏
    #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    #- navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - navigation.expand # 打开Tab时左侧目录全部展开
    #- navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮


  palette:

    # 日间模式
    - scheme: default
      primary: white # 头部菜单栏颜色
      accent: purple # 交互文件高亮颜色
      toggle:
        icon: material/brightness-7
        name: 切换至夜间模式

    # 夜间模式
    - scheme: slate 
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-4
        name: 切换至夜间模式

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences # 代码块高亮插件
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称

#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg
  



extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/chrome
      link: https://chrome.com/
    - icon: fontawesome/brands/zhihu
      link: https://zhihu.com/
    - icon: fontawesome/brands/docker
      link: https://docker.com/
    - icon: fontawesome/brands/bilibili
      link: https://bilibili.com/
    

      


  homepage: https://github.com/

  # 隐藏下栏商标
  generator: false